"""adding phone number

Revision ID: 4c579c10eeb9
Revises: 2c6c3a5198d5
Create Date: 2024-05-09 12:08:53.220734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c579c10eeb9'
down_revision: Union[str, None] = '2c6c3a5198d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
